### ISSUE TITLE
Release please

### ISSUE THREAD

**Issue by mdix** [joramkwak/jquery-no-conflict-exec#1]
Hi,

could you please make a release so we can fix bower dependencies to a version number?

```
git tag v1.0.0
git push --tags
```

Thanks and best
Marc

**Comment by masmrlar** [comment]
Hi,

yes, please add a version tag.

Best
Thomas

**Comment by joramkwak** [comment]
Hi,

I've added a v1.0.0 tag.

Thanks,
Joram
